#! /usr/bin/python

import tkinter as Tkinter
from tkinter import messagebox as tkMessageBox
import random
import logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s') 
logging.disable(logging.DEBUG)

top = Tkinter.Tk()
top.wm_title("Password Generator")

class MyApp():
	def __init__(self):
		logging.debug('Start of MyApp')
		self.Lower    = """abcdefghijklmnopqrstuvwxyz"""
		self.Upper    = """ABCDEFGHIJKLMNOPQRSTUVWXYZ"""
		self.Num      = """1234567890"""
		self.Sym      = """!@#$%^&*(),./<>?'";:"""
		self.startLen = 8
		self.LCalpha = Tkinter.IntVar()
		CB1 = Tkinter.Checkbutton(top, text='Lower Case Alpha', variable=self.LCalpha)
		CB1.grid(row=0, column=0, columnspan=2, pady=3, padx=10)
		CB1.select()
		self.UCalpha = Tkinter.IntVar()
		CB2 = Tkinter.Checkbutton(top, text='Upper Case Alpha', variable=self.UCalpha)
		CB2.grid(row=1, column=0, columnspan=2, pady=3)
		CB2.select()
		self.Numbers = Tkinter.IntVar()
		CB3 = Tkinter.Checkbutton(top, text='Numbers', variable=self.Numbers)
		CB3.grid(row=2, column=0, columnspan=2, pady=3)
		CB3.select()
		self.Symbols = Tkinter.IntVar()
		CB4 = Tkinter.Checkbutton(top, text='Symbols', variable=self.Symbols)
		CB4.grid(row=3, column=0, columnspan=2, pady=3)
		CB4.select()
		Tkinter.Label(top, text='Length').grid(row=4, column=0, pady=3)
		self.Length = Tkinter.Spinbox(top, from_=1, to=99, width=2)
		self.Length.grid(row=4, column=1, pady=3)
		self.Length.delete(0, Tkinter.END)
		self.Length.insert(0, self.startLen)
		Tkinter.Button(top, text='Generate', command=self.MakePW, background='light blue').grid(row=5, column=0, columnspan=2, pady=3)

	def MakePW(self):
		logging.debug('Start of MakePW')
		y = ""
		x = ""
		if self.LCalpha.get() == 1:
			y = y + self.Lower
		if self.UCalpha.get() == 1:
			y = y + self.Upper
		if self.Numbers.get() == 1:
			y = y + self.Num
		if self.Symbols.get() == 1:
			y = y + self.Sym
		for i in range(0, int(self.Length.get())):
			x = x + random.sample(y,1)[0]
		logging.info('Password = ' + x)
		top.clipboard_clear()
		top.clipboard_append(x)
		tkMessageBox.showinfo("Password", "{}\n\nYour Password\nhas been coppied\nto the clipboard".format(x), icon="warning")

if __name__ == "__main__":
	try:
		top.after(100, MyApp)
		top.mainloop()
	except Exception:
		logging.critical('Critical error! Critical error!')
	finally:
		try:
			top.quit()
		except Exception:
			pass
		try:
			quit()
		except Exception:
			pass
